### ISSUE TITLE
How to use it to create your first widget

### ISSUE THREAD

**Issue by 24021438** [haydendonald/NodeRed-Dashbored#1]
I installed your node, but I don't know how to create /example1/example2 and how to use it, can you create a widget through the full process?

**Comment by haydendonald** [comment]
Hi @24021438 i forgot to add that to the readme sorry. You can find a instructional [here](https://github.com/haydendonald/NodeRed-Dashbored). 

For people who don't fully understand NodeRed i suggest to understand how it works before proceeding as this is meant to be an advanced solution (while remaining as simple as possible).

For the specific example you can add the [example JSON](https://github.com/haydendonald/NodeRed-Dashbored/blob/main/examples/defaultExample.json) by going to the menu, click import and paste the JSON in there <img width="415" alt="image" src="https://user-images.githubusercontent.com/12867415/229255749-a94dd055-e34c-4104-a28b-c52b3e153760.png"> 
(remembering to create the server)
